spring.application.name=hazelcat-payment-service-demo

# Default profile: embedded Hazelcast (your JVM IS a cluster member).
spring.profiles.active=${SPRING_PROFILES_ACTIVE:embedded}

server.port=${SERVER_PORT:8081}

# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db?options=-c%20TimeZone=Asia/Kolkata
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate configuration
# spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.web.open-in-view=false

# runs schema.sql on startup
spring.sql.init.mode=always  

# Hazelcast configuration
spring.cache.type=hazelcast

# Management endpoints
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Logging levels
logging.level.com.payment=INFO
logging.level.com.hazelcast=INFO
